basic:
    name: 'https://www.opploans.com batch 5'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs
        - /faqs/what-does-it-mean-to-refinance-my-loan-through-opploans
        - /faqs/i-am-having-trouble-with-bank-verification-what-should-i-do
        - /faqs/what-types-of-credit-products-does-opploans-offer
        - /faqs/what-are-the-interest-rates-and-fees-associated-if-i-receive-a-credit-product-through-opploans
        - /faqs/can-i-apply-over-the-phone
        - /faqs/do-you-allow-cosigners-and-where-does-the-cosigner-sign-on-the-application
        - /faqs/do-i-need-to-send-in-any-documents
        - /faqs/will-show-credit-report
        - /faqs/how-can-i-repay-my-personal-loans
    monitoring:
        days: {  }
        type: daily
        schedule_time: '04:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
